# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2d293f3a5235d2b6c4cad79d27afd7cac1ac586cab7be9d849cb54972930d6735ea99ffebd6b672f7d2b079a9f12e59450b1ea9eb55aad5721a86a2d5e5dac8

test:
  secret_key_base: a6aa0b4aac62bf966ebac08097d1f1a6e1a80ca6fbc857d09b5e0db874d5d564571dbcfc7a8b058fe1a63581b8394e9d176e9a8f95ffeb0eb2ab0a35519a8ec2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
